analysis_name: "Genotator Default Analysis"

# Downloading Specifications
taxon_id: "853"
download_source: "refseq"
download_filename: "../tests/results/test_ncbi_results"

# File Specifications
fastas: "../tests/results/fasta_files"
extension: "fasta"

# Output paths
verified_contigs: "../tests/results/fasta_files_verified"
filtered_contigs: "../tests/results/fasta_files_filtered"
fastani: "../tests/results/fastani"
fastani_thresh: 99
contig_db: "../tests/results/contig_dbs"
annotations: "../tests/results/Annotations"
faas: "../tests/results/FAAs"
gene_calls: "../tests/results/GeneCalls"
gff_final: "../tests/results/GFF3-Final"

# Databases
cazyme_db: "dbs/CAZyme/"
cazyme_mapper: "dbs/CAZyme/fam-substrate-mapping-08252022.tsv"
tigrfam_db: "dbs/TigrFams/AllTigrHmms.hmm"
tigrfam_roles: "dbs/TigrFams/TFAM-Roles.txt"

# Computing
threads: 80

# Logging
log_folder: "../logs"
log_id: "AnnotatingMAGs-DEFAULT"
database_name: "DEFAULT Database Name"
